skip_non_tags: true
environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"
    SDL2_VERSION: '2.0.4'
    SDL2_IMAGE_VERSION: '2.0.1'
    SDL2_MIXER_VERSION: '2.0.1'
    SDL2_TTF_VERSION: '2.0.14'
    USER:
      secure: nmGcMi0wFW8VLkwwxgUvUg==
    PASSWORD:
      secure: 8SYGM59fuZFyAh5bq7sthkVfRPHX6sw8X5s0MJ0r/zM=

  matrix:

    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
    # See: http://www.appveyor.com/docs/installed-software#python

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x" # currently 2.7.9
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.x" # currently 3.3.5
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.x" # currently 3.4.3
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x" # currently 2.7.9
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.0"

    - PYTHON: "C:\\Python33-x64"
      PYTHON_VERSION: "3.3.x" # currently 3.3.5
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.1"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.x" # currently 3.4.3
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.1"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "powershell appveyor\\install.ps1"
  - ps: "Start-FileDownload https://www.libsdl.org/release/SDL2-devel-$($env:SDL2_VERSION)-VC.zip"
  - cmd: "7z x SDL2-devel-%SDL2_VERSION%-VC.zip"
  - ps: "Start-FileDownload https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-$($env:SDL2_IMAGE_VERSION)-VC.zip"
  - cmd: "7z x SDL2_image-devel-%SDL2_IMAGE_VERSION%-VC.zip"
  - cmd: "xcopy /E /Y SDL2_image-%SDL2_IMAGE_VERSION%\\* SDL2-%SDL2_VERSION%"
  - ps: "Start-FileDownload https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-$($env:SDL2_MIXER_VERSION)-VC.zip"
  - cmd: "7z x SDL2_mixer-devel-%SDL2_MIXER_VERSION%-VC.zip"
  - cmd: "xcopy /E /Y SDL2_mixer-%SDL2_MIXER_VERSION%\\* SDL2-%SDL2_VERSION%"
  - ps: "Start-FileDownload https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-$($env:SDL2_TTF_VERSION)-VC.zip"
  - cmd: "7z x SDL2_ttf-devel-%SDL2_TTF_VERSION%-VC.zip"
  - cmd: "xcopy /E /Y SDL2_ttf-%SDL2_TTF_VERSION%\\* SDL2-%SDL2_VERSION%"
  - cmd: "set SDL2_DEVEL_PATH=%APPVEYOR_BUILD_FOLDER%\\SDL2-%SDL2_VERSION%"
  - cmd: "set PATH=C:\\MinGW\\bin;%PATH%"

build: off

test_script:
  - "%WITH_COMPILER% %PYTHON%/python setup.py test"

after_test:
  - "%WITH_COMPILER% %PYTHON%/python setup.py bdist_wheel"

artifacts:
  - path: dist\*

on_success:
  - "%PYTHON%/Scripts/twine upload -u %USER% -p %PASSWORD% dist/* && exit 0"
